{
 "title": "Teamspeak 3 Statistics",
 "description": "Visualise Teamspeak 3 virtual server data provided by collectd",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Server", "query": "collectd.*" },
   { "name": "ID", "query": "collectd.$Server.ts3-*" }
  ]
 },
 "panels": [
  {
   "title": "Voice Clients Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.ts3-$ID.gauge-virtualserver_voiceclientsonline"
    }
   ]
  },
  {
   "title": "Maximum Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.ts3-$ID.gauge-virtualserver_maxclients"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "collectd.$Server.ts3-$ID.gauge-virtualserver_status"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "target": "collectd.$Server.ts3-$ID.gauge-virtualserver_uptime"
    }
   ]
  },
  {
   "title": "Average Packetloss by Type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Packetloss" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_total_packetloss_speech, 0), 'Speech')"
    },
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_total_packetloss_keepalive, 0), 'Keepalive')"
    },
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_total_packetloss_control, 0), 'Control')"
    },
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_total_packetloss_total, 0), 'Overall')"
    },
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_total_ping, 100), 'Client Average RTT')"
    }
   ]
  },
  {
   "title": "Users Online",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_voiceclientsonline, 100), 'Voice Clients')"
    },
    {
     "target": "alias(keepLastValue(collectd.$Server.ts3-$ID.gauge-virtualserver_queryclientsonline, 100), 'Query Clients')"
    }
   ]
  },
  {
   "title": "Traffic Usage by Type",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_received_speech)), '10s', 'sum'), 'Speech (Ingress)')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_received_keepalive, 0)), '10s', 'sum'), 'Keepalive (Ingress)')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_received_control, 0)), '10s', 'sum'), 'Control (Ingress)')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_sent_speech, 0)), '10s', 'sum'), 'Speech (Egress)')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_sent_keepalive, 0)), '10s', 'sum'), 'Keepalive (Egress)')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_sent_control, 0)), '10s', 'sum'), 'Control (Egress)')"
    }
   ]
  },
  {
   "title": "Overall Traffic Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_received_total, 0)), '10s', 'sum'), 'Incoming Traffic')"
    },
    {
     "target": "alias(summarize(derivative(keepLastValue(collectd.$Server.ts3-$ID.gauge-connection_bytes_sent_total, 0)), '10s', 'sum'), 'Outgoing Traffic')"
    }
   ]
  }
 ]
}